### ISSUE TITLE
Update for Eclipse Mars

### ISSUE THREAD

**Issue by mj8w** [mbats/eclipse-buildroot-bundle#21]
The toolchain does not appear to update correctly when using this extension on Mars.1 Release (4.5.1), of course the last update site is for Luna, so I anticipate that there would be incompatibilities.

Mike

**Comment by mj8w** [comment]
Additional details, Update Pkg-config is failing. 

I am importing "Existing Code as Makefile Project". The directory is outside of the buildroot directory; but buildroot is copying it and building it successfully. We just wanted to be able to build it locally as well.

``` bash
!ENTRY org.eclipse.core.jobs 4 2 2016-01-20 08:59:29.128
!MESSAGE An internal error occurred during: "Update Pkg-config external settings provider".
!STACK 0
java.lang.NullPointerException
    at org.eclipse.cdt.managedbuilder.pkgconfig.Activator$1$1.run(Activator.java:101)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.cdt.core 1 0 2016-01-20 08:59:34.717
!MESSAGE Indexed 'My software' (26 sources, 172 headers) in 4.55 sec: 10,420 declarations; 22,051 references; 5 unresolved inclusions; 0 syntax errors; 12 unresolved names (0.037%)
```
